# Install terraform
before_install:
  - curl -sLo /tmp/terraform.zip https://releases.hashicorp.com/terraform/0.11.11/terraform_0.11.11_linux_amd64.zip
  - unzip /tmp/terraform.zip -d /tmp
  - mv /tmp/terraform ~/bin
  - export PATH="~/bin:$PATH"

# Initialize terraform
before_script:
  - cd ./aws/create-ec2/
  - terraform init

# Execute plan for tf
script:
  - ls -ltr
  - terraform plan ./aws/create-ec2/
